### ISSUE TITLE
Create user model and accessor methods

### ISSUE THREAD

**Issue by ahnaf-zamil** [ahnaf-zamil/zenora#1]
Since the `zenora.channels.DMTextChannel` model has a recipients property which consists of one or more user dictionaries, it would be better to convert them to objects with a list comprehension before returning the channel model to the user.

```py
DMTextChannel(id='753254043438284818' last_message_id='753254049305854042' recipients=[{'id': '479287754400989217', 'username': 'Ahnaf', 'avatar': '9ab336b1e0506f6549d708591991d195', 'discriminator': '4346', 'public_flags': 128}])
```

**Comment by StarrMan303** [comment]
So do you want to create a whole new user model that will be accessed by it's ID or do you just want to convert the recipients to their own objects?

**Comment by ahnaf-zamil** [comment]
> So do you want to create a whole new user model that will be accessed by it's ID or do you just want to convert the recipients to their own objects?

Hey thanks for dropping by! I really need some help with this module. I would like to have a whole user object that can be accessed by it's ID because there aren't a lot of helpful things in the recipients object

**Comment by StarrMan303** [comment]
> > So do you want to create a whole new user model that will be accessed by it's ID or do you just want to convert the recipients to their own objects?
> 
> Hey thanks for dropping by! I really need some help with this module. I would like to have a whole user object that can be accessed by it's ID because there aren't a lot of helpful things in the recipients object

No problem, I just wanted to help. So I'm gonna get to work and make a pull request after testing it
