### ISSUE TITLE
Using Python Interpreter of PyCharm gives error during install

### ISSUE THREAD

**Issue by Cupara** [ahnaf-zamil/zenora#10]
When trying to use the Python Interpreter of PyCharm to add the Zenora package I get the following error:
`Installing Zenora...

[    ] Installing...
[=   ] Installing Zenora...
[==  ] Installing Zenora...
[=== ] Installing Zenora...
[ ===] Installing Zenora...
[  ==] Installing Zenora...
[   =] Installing Zenora...
[    ] Installing Zenora...
[   =] Installing Zenora...
[  ==] Installing Zenora...
[ ===] Installing Zenora...
[====] Installing Zenora...
[=== ] Installing Zenora...
[==  ] Installing Zenora...
[=   ] Installing Zenora...
[    ] Installing Zenora...
[=   ] Installing Zenora...
[==  ] Installing Zenora...
[=== ] Installing Zenora...
[ ===] Installing Zenora...
[  ==] Installing Zenora...
[   =] Installing Zenora...
[    ] Installing Zenora...
Error:  An error occurred while installing Zenora!

Error text: 

ERROR: Could not find a version that satisfies the requirement zenora (from versions: none)
ERROR: No matching distribution found for zenora

Installation Failed `

**Comment by ahnaf-zamil** [comment]
Which Python version are you using? Please include the following information when creating an issue: Your Operating System, Your Python version

**Comment by Cupara** [comment]
Windows 10
Python 3.7.9 and 3.8

**Comment by ahnaf-zamil** [comment]
It's probably because of your 3.7 installation. Zenora requires 3.8 at least, and I think pip is using Py 3.7 as the default py version, so it can't find Zenora :/
