### ISSUE TITLE
Tests are not Responding to Local Changes in Zenora RESTAPI

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#12]
**Describe the bug**

**To Reproduce**
1. Go to tests/unit
2. pip uninstall zenora
3. see error
AND
(in case you don't see an error)
1. go to impl/rest
2. Change response of any function to "dog"
3. go to tests/unit
4. change the test for the function to except "dog"
5. see the error 
**Expected behavior**
The test should be working of the local module, on my machine the seem to work from the PyPI.
**Screenshots**
![image](https://user-images.githubusercontent.com/42012902/93162381-ae90fa00-f6e2-11ea-98cb-cada9ae60263.png)

 - OS: Windows10
 - Python Version [3.8]

**Comment by MaksymKarunos** [comment]
A possible solution can be found here:
https://stackoverflow.com/questions/41276067/importing-class-from-another-file

**Comment by ahnaf-zamil** [comment]
You have to access Zenora from the root folder. Right now you are in ``zenora\tests\unit\``. So do ``cd ../../`` in the terminal and go go the ``zenora\`` folder

**Comment by ahnaf-zamil** [comment]
I made a video showing you how to fix this issue: https://www.youtube.com/watch?v=ku4ugNbe6V4&feature=youtu.be

once everything is working, I will close this issue
