### ISSUE TITLE
How can you get the guilds of the user?

### ISSUE THREAD

**Issue by ghost** [ahnaf-zamil/zenora#13]
How can you get the guilds of the user that has authenticated, Using zenora.

**Comment by ghost** [comment]
I've just realized it was because i was using the pip version of zenora.

**Comment by ghost** [comment]
Welp, I have no idea how i could get the guilds

**Comment by ghost** [comment]
I got it to work.

**Comment by kenyati** [comment]
Could you shed some light bc Im having the same issue

**Comment by ahnaf-zamil** [comment]
Use the GitHub version of Zenora

**Comment by asdu5asg6da8sjd** [comment]
> @kenyati Could you shed some light bc Im having the same issue

use `git clone https://github.com/ahnaf-zamil/zenora` while in your project directory, it'll give you the latest github version, which has an api for guilds

you can also use `pip install git+https://gitlab.com/ahnaf-zamil/zenora` in any directory
