### ISSUE TITLE
Documentation Misses the Travis CI Build Status Button and other Minor Formatting Issues

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#14]
**Describe the bug**
Documentation Misses the Travis CI Build Status Button and other Minor Formatting Issues

**Screenshots**
![image](https://user-images.githubusercontent.com/42012902/93273430-d7b69680-f785-11ea-82fd-54835b6919f1.png)

**Comment by ahnaf-zamil** [comment]
Saw the issue. It will be fixed quickly.

**Comment by MaksymKarunos** [comment]
Leave it for new contributors, at least give them a few days, and then we can fix it.

**Comment by ahnaf-zamil** [comment]
To work on docs, they need to know how Sphinx works because that's the documentation tool we use

**Comment by MaksymKarunos** [comment]
Let's assign Lunar, let's see if hi will be interested in contributing that way, what do you think?

**Comment by StarrMan303** [comment]
I will work on this issue. Leave it to me!
