### ISSUE TITLE
Contributing.MD misses requirements on Pre-Commit Hooks Installation 

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#15]
**Describe the bug**
Documentation misses requirements for git hooks installation. 

1. Install pre-commit: `pip install pre-commit`
2. Add pre-commit to `requirements.txt` 
3. Define `.pre-commit-config.yam`l with the hooks, you want to include.
4. Execute pre-commit install to install git hooks in your `.git/ directory.`

(I am not sure, but I believe there are other dependencies to be installed)

**Comment by ahnaf-zamil** [comment]
Solved the issue with [this commit.](https://github.com/ahnaf-zamil/zenora/commit/1086e42e9b3b8016dcf67d4d0b29cb2432978573) Since it's fixed, I'm closing this issue
