### ISSUE TITLE
Rediesgn Folder Hierarchy

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#18]
**Is your feature request related to a problem? Please describe.**
Our main folder got to mess up. we need to sort and put files in a more structured way.

**Comment by ahnaf-zamil** [comment]
By main folder, do you mean root folder? The root folder is messed up in all projects because all the config files are there

**Comment by MaksymKarunos** [comment]
Ok. I will reopen once I see something out of place.
