### ISSUE TITLE
'message' error

### ISSUE THREAD

**Issue by itsinhaleyo** [ahnaf-zamil/zenora#18]
'message' error popping up after setting up environmental variables?
could that have had something to do with it?

**Comment by itsinhaleyo** [comment]
For future reference for people who might have gotten this error, it was due to my clientsecret being set as the token on accident

**Comment by ahnaf-zamil** [comment]
I have attempted to fix this error in the most recent release a few days ago. You should try installing the latest version of Zenora from PyPi and let me know if you still run into it.

**Comment by itsinhaleyo** [comment]
I will install the latest version, i already found my issue though. Love what you got done here ❤️

**Comment by itsinhaleyo** [comment]
> I will install the latest version, i already found my issue though. Love what you got done here ❤️

As a fellow coding user trying to get through previously unchallenged hurdles and succeeding, keep your work up, you make things amazing for others

**Comment by itsinhaleyo** [comment]
> I have attempted to fix this error in the most recent release a few days ago. You should try installing the latest version of Zenora from PyPi and let me know if you still run into it.

And actually this is what helped me find this issue, god these repo commit logs help a ton!

**Comment by ahnaf-zamil** [comment]
Thanks a lot for the kind words, and I'm glad your issue was solved. I'm closing this issue now. If there are problems, feel free to make another issue or contact me through my email `ahnaf@ahnafzamil.com` :D
