### ISSUE TITLE
get_current_user()/get_channel() Return Invalid Response| Python3.8 | Zenora 0.0.33v | Ubuntu 18.04 / Ubuntu 20.4 / MAC OS 10.3

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#21]
**Describe the bug**
Zenora 0.0.33v will not work without core folders. 
I have tried: 
Conda virtual environments: python3.6/3.7/3.8
Mac OS 10.3 python3.6/3.7/3.8
Ubuntu 20.4 python3.6/3.7/3.8
Ubuntu 18.4 pytho3.6/3.7/3.8

**To Reproduce**
1. Create a new work folder ( MUST NOT BE IN THE SAME ENVIRONMENT AS ZENORA ROOT )
2. python3.8 -m pip install zenora / pip install zenora / pip3 install zenora
```
import zenora

api = zenora.RESTAPI(
    token="I_removed_token_for_safety", token_type="User"
)

me = api.get_current_user()

print(me)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/42012902/93517444-78799300-f8f9-11ea-949e-13ea45ee0ef8.png)

 - OS: Ubuntu 18.04 / Ubuntu 20.4 / MAC OS 10.3
 - Python Version 3.6/3.7/3.8

**Comment by MaksymKarunos** [comment]
Just tested on my new Ubuntu OS that we installed yesterday.

`sudo python3.8 -m pip install zenora`

The same error

**Comment by MaksymKarunos** [comment]
The code starts to return this error on the HEAD of the commit version:

![image](https://user-images.githubusercontent.com/42012902/93549708-e47aec00-f937-11ea-9518-4516f9e93450.png)

**Comment by ahnaf-zamil** [comment]
Dude the token type should be either "Bot" or "Bearer". The current user endpoint requires the token type endpoint because it's accessible from the bot and bearer tokens. There is not too type called "User".

```py
import zenora

api = zenora.RESTAPI(
    token="I_removed_token_for_safety", token_type="Bot"
)

me = api.get_current_user()

print(me)
```

**Comment by MaksymKarunos** [comment]
It still does not work with a Bot.

**Comment by MaksymKarunos** [comment]
It does not work a Bearer either.

**Comment by ahnaf-zamil** [comment]
Bearer tokens are for Oauth2. They won't work with Bot or User tokens. Also Zenora doesn't support user tokens because it's a type of self-botting which is against Discord TOS.
