### ISSUE TITLE
Invalid Token Exception Handler

### ISSUE THREAD

**Issue by itsinhaleyo** [ahnaf-zamil/zenora#21]
Hello, Im just checking to see if you made any exception handlers for the "Invalid Token" Error?
I cant seem to find anything on how i could do this.

**Comment by ahnaf-zamil** [comment]
For invalid token, the `AuthenticationError` class is adequate. It's thrown whenever the API gives you a 401, which means you aren't authenticated properly with a token.

Also, kindly read the note on the README. The project's activity has been moved to GitLab, and it won't be active on GitHub.
