### ISSUE TITLE
How can i check if token is valid / refresh it?

### ISSUE THREAD

**Issue by TheGamer3514** [ahnaf-zamil/zenora#25]
I am wondering how i can check if token is valid / refresh it?

**Comment by ahnaf-zamil** [comment]
Hello, thank you for making this issue to ask a question.

For now, the best way to check if a token is valid is to make an `APIClient` instance with the token. Whenever an instance is created and the `validate_token` argument is not set to `False` explicitly, it will send a request to the Discord API to validate the token. If the token is not valid, it will throw a `zenora.exceptions.AuthenticationError`

https://github.com/ahnaf-zamil/zenora/blob/ebe31c7aadb2d27f30c0f77dca8d0ffd44037ed3/zenora/client.py#L29-L57

If there's anything else I can help you with, feel free to ask. Have a good one!
