### ISSUE TITLE
Message Unit Tests Won't Run on Mocked API calls

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#26]
**Describe the bug**
When you run unit tests in test_messages.py they won't succeed with testing parameter set to false.

**To Reproduce**
1. `git checkout added-message object`
2. `python3.8 tests.unit.test_messages`
3. Tests won't pass with testing set to false if API instance is created with testing set to False.

 - OS: [e.g. Ubuntu 16.04]
 - Python Version [e.g. 3.8]

**Comment by ahnaf-zamil** [comment]
When instantiating an API instance, you **have** to set the parameter `testing` to true because we are testing. It's there for a reason. We need to mock those API calls

**Comment by MaksymKarunos** [comment]
Yes but it does not work that way.
