### ISSUE TITLE
client.users.get_my_guilds() returns empty list

### ISSUE THREAD

**Issue by Fluffik3666** [ahnaf-zamil/zenora#28]
# Issue
### My discord account I am using to sign in is in a lot of guilds and so is the bot user.
> ### I am making a discord bot website, this error isn't critical to me as I do not need the function ***(yet)***.

**Comment by ahnaf-zamil** [comment]
Hello! 

Are you using Oauth? Also, what are the Oauth scopes you have set in your authorisation link? If you don't have the "guilds" scope set in the Oauth link, you may not receive the guilds.

**Comment by Fluffik3666** [comment]
Ah, I see. I'm unavailable to check now but will do soon. That is probably the issue:)

**Comment by Fluffik3666** [comment]
yep it works thanks
