### ISSUE TITLE
Add Documentation for the Emoji class

### ISSUE THREAD

**Issue by gauravndabhade** [ahnaf-zamil/zenora#28]
**Describe**
A clear and concise description of Emojis in Zenora.

**Comment by ahnaf-zamil** [comment]
I will be working on this issue after I get to my destination. As I'm typing, I'm in my family car going to another district in an 8 hour journey. Puts a lot of stress on me. But as soon as I get there and take some rest, I will be back working with full speed so don't worry 😄

**Comment by ahnaf-zamil** [comment]
Done!
