### ISSUE TITLE
Move response error handlers to utils

### ISSUE THREAD

**Issue by StarrMan303** [ahnaf-zamil/zenora#3]
Currently all the API response's errors have been handled in their respective models but that makes the code messy. It would be better to handle the errors in a separate utils file since all error codes are the same in case of snowflake and a few 

# Tasks

- [X] Remove error handling from ``__init__`` of the respective models. 

- [X] Make a separate file in the ``zenora.utils`` folder and handle the errors there.

**Comment by ahnaf-zamil** [comment]
I will be working on moving the error handlers to utils. Thanks for raising this issue

**Comment by ahnaf-zamil** [comment]
Issue has been fixed with commit [5423b06705811d22b5780ec536f5af9969259e66](https://github.com/ahnaf-zamil/zenora/commit/5423b06705811d22b5780ec536f5af9969259e66). Also added a welcome message on module import in the ``__init__.py`` file. Issue will be closed.

Thank you
