### ISSUE TITLE
Feature Request: Design Contribution Guidlines

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#5]
Design CONTRIBUTING.md

**Comment by StarrMan303** [comment]
I want to be assigned to this issue. Making contribution guidelines is easy.

**Comment by ahnaf-zamil** [comment]
I've assigned you Starrman303 to make the contribution guidelines

**Comment by StarrMan303** [comment]
Created pull request for closing this issue. Please review it
